#!/usr/bin/env bash
set -Eeuo pipefail

EXTENSION_NAME="publish-drawio-skill"
GIGACODE_HOME="${GIGACODE_HOME:-$HOME/.gigacode}"
GIGACODE_BIN="${GIGACODE_BIN:-$GIGACODE_HOME/bin/gigacode}"
GIGACODE_SKILLS_DIR="${GIGACODE_SKILLS_DIR:-$GIGACODE_HOME/skills}"
GIGACODE_EXTENSIONS_DIR="${GIGACODE_EXTENSIONS_DIR:-$GIGACODE_HOME/extensions}"
GIGACODE_EXTENSION_SOURCES_DIR="${GIGACODE_EXTENSION_SOURCES_DIR:-$GIGACODE_HOME/extension-sources}"
GIGACODE_BACKUP_DIR="${GIGACODE_BACKUP_DIR:-$GIGACODE_HOME/backups/drawio-agent-extension}"
backup_path=""
dry_run=0
force=0

usage() {
  cat <<'EOF'
Usage:
  rollback_drawio_agent_extension.sh [--backup PATH | --latest] [--dry-run] [--force]

Without --backup, the newest installer backup is selected. The command removes
the current agent extension and restores the previous skill/extension state.
EOF
}

log() { printf '[drawio-extension:rollback] %s\n' "$*"; }
die() { printf '[drawio-extension:rollback] ERROR: %s\n' "$*" >&2; exit 1; }
quote_cmd() { printf ' %q' "$@"; printf '\n'; }
run() { if (( dry_run )); then printf '[dry-run]'; quote_cmd "$@"; else "$@"; fi; }

path_is_within() {
  local child="$1" parent="$2"
  [[ -n "$child" && -n "$parent" && "$child" != "/" && "$parent" != "/" ]] || return 1
  case "$child" in "$parent"|"$parent"/*) return 0 ;; *) return 1 ;; esac
}

safe_remove_tree() {
  local target="$1" allowed_parent="$2"
  path_is_within "$target" "$allowed_parent" || die "Refusing to remove unsafe path: $target"
  [[ "$target" != "$allowed_parent" ]] || die "Refusing to remove parent directory: $target"
  run rm -rf -- "$target"
}

help_supports() {
  local token="$1" help_text="$2"
  grep -Eq -- "(^|[[:space:],])${token//-/\\-}([=[:space:],]|$)" <<<"$help_text"
}

extensions_list_contains() {
  "$GIGACODE_BIN" extensions list 2>/dev/null | grep -Fq "$EXTENSION_NAME"
}

native_uninstall() {
  local help_text args=(extensions uninstall "$EXTENSION_NAME")
  help_text="$($GIGACODE_BIN extensions uninstall --help 2>&1 || true)"
  help_supports '--yes' "$help_text" && args+=(--yes)
  help_supports '--force' "$help_text" && args+=(--force)
  run "$GIGACODE_BIN" "${args[@]}"
}

native_install() {
  local source="$1" help_text
  local args=(extensions install "$source")
  help_text="$($GIGACODE_BIN extensions install --help 2>&1 || true)"
  help_supports '--yes' "$help_text" && args+=(--yes)
  help_supports '--force' "$help_text" && args+=(--force)
  run "$GIGACODE_BIN" "${args[@]}"
}

while (($#)); do
  case "$1" in
    --backup) [[ $# -ge 2 ]] || die "--backup requires PATH"; backup_path="$2"; shift 2 ;;
    --latest) backup_path=""; shift ;;
    --dry-run) dry_run=1; shift ;;
    --force) force=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done

[[ -x "$GIGACODE_BIN" ]] || die "GigaCode CLI not executable: $GIGACODE_BIN"
if [[ -z "$backup_path" ]]; then
  [[ -d "$GIGACODE_BACKUP_DIR" ]] || die "No backup directory: $GIGACODE_BACKUP_DIR"
  backup_path="$(find "$GIGACODE_BACKUP_DIR" -mindepth 1 -maxdepth 1 -type d -print | LC_ALL=C sort | tail -n 1)"
  [[ -n "$backup_path" ]] || die "No installer backups found"
fi
backup_path="$(cd "$backup_path" 2>/dev/null && pwd)" || die "Backup not found: $backup_path"
backup_root="$(cd "$GIGACODE_BACKUP_DIR" 2>/dev/null && pwd)" || die "Backup root not found: $GIGACODE_BACKUP_DIR"
path_is_within "$backup_path" "$backup_root" || die "Backup must be inside $backup_root"
[[ -f "$backup_path/state.env" ]] || die "Backup state file is missing: $backup_path/state.env"
[[ ! -e "$backup_path/.rolled-back" || $force -eq 1 ]] || die "Backup was already rolled back; use --force to repeat"

# state.env is generated by the installer with shell-escaped values and lives
# under the guarded backup root.
# shellcheck disable=SC1090
source "$backup_path/state.env"
[[ "$EXTENSION_NAME" == "publish-drawio-skill" ]] || die "Unexpected extension in backup state"

legacy="$GIGACODE_SKILLS_DIR/drawio-skill"
extension_dir="$GIGACODE_EXTENSIONS_DIR/$EXTENSION_NAME"
current_source="$GIGACODE_EXTENSION_SOURCES_DIR/$EXTENSION_NAME/current"

# Prove that the selected backup is complete before uninstalling or deleting
# anything from the active GigaCode directories.
for flag in HAD_LEGACY_SKILL HAD_EXTENSION_DIR HAD_SOURCE_DIR HAD_NATIVE_EXTENSION; do
  value="${!flag:-}"
  [[ "$value" == 0 || "$value" == 1 ]] || die "Invalid $flag value in backup state"
done
if [[ "$HAD_LEGACY_SKILL" == 1 && ! -e "$backup_path/legacy-skill" ]]; then
  die "Legacy skill backup is missing"
fi
if [[ "$HAD_SOURCE_DIR" == 1 && ! -e "$backup_path/source-current" ]]; then
  die "Previous extension source backup is missing"
fi
if [[ "$HAD_EXTENSION_DIR" == 1 && ! -e "$backup_path/extension-dir" ]]; then
  die "Previous extension directory backup is missing"
fi
restore_source_backup=""
if [[ "$HAD_SOURCE_DIR" == 1 ]]; then
  restore_source_backup="$backup_path/source-current"
elif [[ "$HAD_EXTENSION_DIR" == 1 ]]; then
  restore_source_backup="$backup_path/extension-dir"
fi
if [[ "$HAD_NATIVE_EXTENSION" == 1 && -z "$restore_source_backup" ]]; then
  die "Previous native extension has no restorable source"
fi

if extensions_list_contains; then
  log "Uninstalling current $EXTENSION_NAME"
  native_uninstall
fi
[[ -e "$extension_dir" ]] && safe_remove_tree "$extension_dir" "$GIGACODE_EXTENSIONS_DIR"
if [[ -L "$current_source" || -e "$current_source" ]]; then
  safe_remove_tree "$current_source" "$(dirname "$current_source")"
fi
if [[ -n "${INSTALLED_SOURCE_PATH:-}" && -e "$INSTALLED_SOURCE_PATH" ]]; then
  path_is_within "$INSTALLED_SOURCE_PATH" "$GIGACODE_EXTENSION_SOURCES_DIR/$EXTENSION_NAME" || die "Unsafe installed source path in backup state"
  safe_remove_tree "$INSTALLED_SOURCE_PATH" "$GIGACODE_EXTENSION_SOURCES_DIR/$EXTENSION_NAME"
fi

[[ -e "$legacy" ]] && safe_remove_tree "$legacy" "$GIGACODE_SKILLS_DIR"
if [[ "${HAD_LEGACY_SKILL:-0}" == 1 ]]; then
  run mkdir -p -- "$GIGACODE_SKILLS_DIR"
  run cp -a -- "$backup_path/legacy-skill" "$legacy"
fi

restore_source=""
if [[ "${HAD_SOURCE_DIR:-0}" == 1 ]]; then
  run mkdir -p -- "$(dirname "$current_source")"
  run cp -a -- "$backup_path/source-current" "$current_source"
  restore_source="$current_source"
fi
if [[ "${HAD_EXTENSION_DIR:-0}" == 1 ]]; then
  run mkdir -p -- "$GIGACODE_EXTENSIONS_DIR"
  run cp -a -- "$backup_path/extension-dir" "$extension_dir"
  # If this was the only previous source, register from the immutable backup,
  # not from the destination that GigaCode may replace during installation.
  [[ -z "$restore_source" ]] && restore_source="$backup_path/extension-dir"
fi
if [[ "${HAD_NATIVE_EXTENSION:-0}" == 1 ]]; then
  log "Registering the restored extension through GigaCode"
  native_install "$restore_source"
fi

run touch "$backup_path/.rolled-back"
log "Rollback completed from $backup_path"
if [[ "${HAD_LEGACY_SKILL:-0}" == 1 ]]; then
  log "The previous legacy skill was restored. Do not reinstall the agent extension at the same time."
fi
